version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo running apt-get update ...
      - apt-get update
      - echo running npm install ...
      - npm install
      - echo installing serveless framework
      - npm install -g serverless
    run-as: root
  pre_build:
    commands:
      - echo HVGN backend deploy beginning at `date`
#      - API_KEY_TIMESTAMP=$(date +%s)
#      - echo $API_KEY_TIMESTAMP
    run-as: root
  build:
    commands:
      - mkdir artifacts
      - mkdir artifacts/dev
      - mkdir artifacts/prod
      - echo packaging dev artifacts
      - serverless package --package artifacts/dev -s dev --verbose
      - echo packaging prod artifacts
      - serverless package --package artifacts/prod -s prod --verbose
      - ls -al
      - ls -al artifacts/dev
    run-as: root
  post_build:
    commands:
      - echo HVGN backend succssfully completed at `date`
    run-as: root
artifacts:
  files:
    - artifacts/**/*
    - serverless.yml
    - deploy/**
    - package.json