version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo running apt-get update ...
      - apt-get update
      - echo running npm install ...
      - npm install
    run-as: root
  pre_build:
    commands:
      - echo HVGN backend deploy beginning at `date`
  build:
    commands:
  post_build:
    commands:
      - echo HVGN backend succssfully completed at `date`