version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo running apt-get update ...
      - apt-get update
      - echo running npm install ...
      - npm install
      - echo installing serveless framework
      - npm install -g serverless
    run-as: root
  pre_build:
    commands:
      - echo HVGN backend deploy beginning at `date`
    run-as: root
  build:
    commands:
      - mkdir artifacts
      - mkdir artifacts/dev
      - mkdir artifacts/prod
      - echo packaging dev artifacts
      - export DEV_API_KEY=$(aws ssm get-parameter --name "/api.hvgn.net/dev/apikey" --with-decryption | jq -r '.Parameter.Value' )
      - sls package --package artifacts/dev -s dev -v --api_key $DEV_API_KEY
      - echo packaging prod artifacts
      - export PROD_API_KEY=$(aws ssm get-parameter --name "/api.hvgn.net/prod/apikey" --with-decryption | jq -r '.Parameter.Value' )
      - sls package --package artifacts/prod -s prod -v --api_key $PROD_API_KEY
    run-as: root
  post_build:
    commands:
      - echo HVGN backend succssfully completed at `date`
    run-as: root
artifacts:
  files:
    - artifacts/**/*
    - serverless.yml
    - deploy/**
    - package.json