version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo running apt-get update ...
      - apt-get update
      - echo running npm install ...
      - npm install
      - echo installing serverless framework
      - npm install -g serverless
    run-as: root
  pre_build:
    commands:
      - echo HVGN backend deploy dev beginning at `date`
      - SLS_DEBUG=*
    run-as: root
  build:
    commands:
      - mkdir -p .serverless
      - cp -r $CODEBUILD_SRC_DIR/artifacts/$env/* ./.serverless
      - serverless create_domain
      - serverless deploy --stage $env --package .serverless -v
    run-as: root
  post_build:
    commands:
      - echo HVGN backend deploy dev succssfully completed at `date`
    run-as: root