version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo running apt-get update ...
      - apt-get update
      - echo running npm install ...
      - npm install
      - echo installing serverless framework
      - npm install -g serverless
      - echo installing serverless plugins
      - npm install -g serverless-offline serverless-pseudo-parameters serverless-domain-manager 
    run-as: root
  pre_build:
    commands:
      - echo HVGN backend deploy dev beginning at `date`
    run-as: root
  build:
    commands:
      - ls -al
      - cat serverless.yml
      - pwd
      - ls $CODEBUILD_SRC_DIR/artifacts/$env
      - serverless deploy --stage $env --package $CODEBUILD_SRC_DIR/artifacts/$env -v
    run-as: root
  post_build:
    commands:
      - echo HVGN backend deploy dev succssfully completed at `date`
    run-as: root